// config/pricingTiers.js
module.exports = [
  {
    id: "tier_10_1000",
    name: "Base",
    users: 10,
    assets: 1000,
    priceMonthly: 15,
    priceYearly: 216,
    currency: "USD",
    popular: false,

    features: [
      "Up to 1 Admin User",
      "Up to 1,000 Hardware Assets",
      "Up to 1,000 Software Assets",
      "Multi-Location Management",
      "Complete Lifecycle Tracking",
      "SaaS Usage & License Tracking",
      "Invoice Upload & Management",
      "Check-in / Check-out Tracking",
      "Email Support",
    ],
  },

  {
    id: "tier_20_2500",
    name: "Grow",
    users: 20,
    assets: 2500,
    priceMonthly: 30,
    priceYearly: 432,
    currency: "USD",
    popular: true,

    features: [
      "Up to 5 Admin Users",
      "Up to 2,500 Hardware Assets",
      "Up to 2,500 Software Assets",
      "Multi-Location Management",
      "Complete Lifecycle Tracking",
      "SaaS Usage & License Tracking",
      "Invoice Upload & Management",
      "Role-Based Access (RBAC)",
      "Check-in / Check-out Tracking",
      "Dedicated Account Manager",
      "Full Integrations",
      "Import & Export",
      "Dedicated Support",
    ],
  },

  {
    id: "tier_50_5000",
    name: "Omni",
    users: 50,
    assets: 5000,
    priceMonthly: 80,
    priceYearly: 960,
    currency: "USD",
    popular: false,

    features: [
      "Unlimited Hardware Assets",
      "Unlimited Software Assets",
      "Unlimited Admin Users",
      "Multi-Location Management",
      "Complete Lifecycle Tracking",
      "SaaS Usage & License Tracking",
      "Invoice Upload & Management",
      "QR Code & Barcode Labeling",
      "Role-Based Access (RBAC)",
      "Check-in / Check-out Tracking",
      "SAML / SSO Security",
      "Automatic Cloud Backups",
      "Dedicated Account Manager",
      "Full Integrations",
      "Import & Export",
      "Priority Support",
    ],
  },
];
