// config/pricingTiers.js
module.exports = [
  {
  id: "tier_trial_internal",
  key: "trial",
  name: "Trial",
  admins: 1,
  hardwareAssets: 1000,
  softwareAssets: 1000,
  priceMonthly: 0,
  priceYearly: 0,
  currency: "USD",
  popular: false,
  internal: true,        // 🔥 important flag
  features: [
    "Full Base Plan Access (7 Days)",
  ],
},
  {
    id: "tier_10_1000",
    key: "base",
    name: "Base",
    admins: 1,
    hardwareAssets: 1000,
    softwareAssets: 1000,
    priceMonthly: 15,
    priceYearly: 12,
    currency: "USD",
    popular: false,

    features: [
      "Up to 1000 Hardware Assets",
      "Up to 1000 Software Assets",
      "Up to 1 Admin User",
      "Multi-Location Management",
      "Complete Lifecycle Tracking",
      "SaaS Usage & License Tracking",
      "Role-Based Access (RBAC)",
      // "Invoice Upload & Management",
      "SAML / SSO Security",
      "Check-in / Check-out Tracking",
      "Dedicated Account Manager",
      "Import & Export",
      "Email Support",
    ],
  },

  {
    id: "tier_20_2500",
    key: "grow",
    name: "Grow",
    admins: 5,
    hardwareAssets: 2500,
    softwareAssets: 2500,
    priceMonthly: 30,
    priceYearly: 25,
    currency: "USD",
    popular: true,

    features: [
      "Up to 2500 Hardware Assets",
      "Up to 2500 Software Assets",
      "Up to 5 Admin Users",
      "Multi-Location Management",
      "Complete Lifecycle Tracking",
      "SaaS Usage & License Tracking",
      // "Invoice Upload & Management",
      "Role-Based Access (RBAC)",
      "Check-in / Check-out Tracking",
      "SAML / SSO Security",
      "Dedicated Account Manager",
      "Import & Export",
      "Dedicated Support",
    ],
  },

  {
    id: "tier_50_5000",
    key: "omni",
    name: "Omni",
    admins: "unlimited",
    hardwareAssets: "unlimited",
    softwareAssets: "unlimited",
    priceMonthly: 80,
    priceYearly: 75,
    currency: "USD",
    popular: false,

    features: [
      "Unlimited Hardware Assets",
      "Unlimited Software Assets",
      "Unlimited Admin Users",
      "Multi-Location Management",
      "Complete Lifecycle Tracking",
      "SaaS Usage & License Tracking",
      // "Invoice Upload & Management",
      // "QR Code & Barcode Labeling",
      "Role-Based Access (RBAC)",
      "Check-in / Check-out Tracking",
      "SAML / SSO Security",
      // "Automatic Cloud Backups",
      "Dedicated Account Manager",
      "Import & Export",
      "Priority Support",
    ],
  },
];
  