const defaultLocations = [
    { name : "United States" },
    { name : "New york city" },
	{ name : "Canada" },
    { name : "Ottawa" },
	{ name : "India" },
    { name : "delhi" },
	{ name : "France" },
    { name : "Paris" },
	{ name : "Germany" },
    { name : "Berlin" },
	{ name : "Italy" },
    { name : "Rome" },
	{ name : "United Kingdom" },
    { name : "London" },
	{ name : "Spain" },
    { name : "Madrid" },
]
const defaultCategories = [
    { name : "Accessories" },
    { name : "Desktop applications" },
    { name : "End-user device" },
    { name : "Enterprise systems" },
    { name : "Licenses & entitlements" },
    { name : "Operating systems" },
    { name : "Saas" },
    { name : "Machinery" },
    { name : "Robotics" },
    { name : "Equipment" },
    { name : "Electronics" },
    { name : "Servers & storage" },
    { name : "Security & Safety" },
    { name : "User-End-Device" },
]
const defaultDepartments = [ 
    { name : "Sales" },
    { name : "Research & development" },
    { name : "Product management" },    
    { name : "Operations/administration" },
    { name : "Marketing" },
    { name : "Logistics / warehouse" },
    { name : "Information technology" },
    { name : "Human resources (hr)" },  
    { name : "Finance & accounting" },
    { name : "Customer support" },
]
const defaultStatuses = [            
    { name : "Sold / Donated" },
    { name : "Missing / Stolen" },
    { name : "In Stock" },
    { name : "In Repair" },
    { name : "Disposed" },
    { name : "Active (In use)" },
]
const defaultUnits = [
    { name : "User / seat" },
    { name : "Terabytes (TB)" },
    { name : "Piece" },
    { name : "Gigabytes (GB)" },
    { name : "Device / endpoint" },
    { name : "Cores / Sockets" },
    { name : "Concurrent user" },
]

module.exports = { defaultUnits , defaultCategories , defaultDepartments , defaultLocations , defaultStatuses }